version: '2'

services:
  todo.api:
    image: todo.api
    build:
      context: ./Todo.API
      dockerfile: Dockerfile

  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "your_password"
      ACCEPT_EULA: "Y"
